### ISSUE TITLE
How did you generate gt edge?

### ISSUE THREAD

**Issue by YiChuanChang** [Karel911/TRACER#1]
Hi
This is really an amazing work. I would like to reproduce your result. But I found you did not mentioned how you generate gt edge data in the paper. And I don't have the permission to access the gt edge data link in README.

Of course, it would be wonderful if you can provide the full pre-trained model.

**Comment by Karel911** [comment]
Hi, thank you for your interest in our research.
We modified the download link and now you can download the edge GT.
We have uploaded pre-trained model of TRACER-Efficient-0 to 7.
When you initialize the TRACER, the pre-trained model will be downloaded.

Thanks.

**Comment by YiChuanChang** [comment]
Thanks for your fast and kindly reply.
I thought "TRACER-Efficient-0 to 7" is the pre-trained weight for the backbone. Cause when I tried to test it with `python main.py test --exp_num 0 --arch 0 --img_size 320`, it would ask me to have `results/DUTS/TE0_0/best_model.pth`. I cannot found your weight for this. Or I missed something.

**Comment by Karel911** [comment]
You can manually get the pre-trained model from [here](https://github.com/Karel911/TRACER/releases/tag/v1.0).
Please change the model name as `best_model.pth` and put the weights to the path `results/DUTS/TEx_0/best_model.pth` (here, the x means the model scale e.g., 0 to 7).
Input image size for each model is listed in readme.md -> configurations.
