### ISSUE TITLE
Reproducing paper results of TE7

### ISSUE THREAD

**Issue by aviadmx** [Karel911/TRACER#15]
Tried training using the same hyper params of the paper in order to reproduce results on the DUTS-TE split for example.  
Apart from batch size which had to be reduced to 8, all other params were the same.  
However, I reach inferior results:
```
Dataset:DUTS
Test Loss:1.457 | MAX_F:0.903 | AVG_F:0.873 | MAE:0.030 | S_Measure:0.891, time: 68938.211s
```
This is the training command I used:
```
python main.py train --exp_num 1 --arch 7 --img_size 640 --model_path /data/outputs/TRACER --data_path /data/datasets/TRACER/ --multi_gpu true --num_workers 12 --batch_size 8
```
The best model was achieved at epoch 14 as stated in the logs:
```
Best Val Epoch:14 | Val Loss:38.960 | Val MAE:0.019
```
And the training concluded after epoch 24 due to early stopping mechanism.

**Comment by Karel911** [comment]
Hi,
As you mentioned above, the small batch size results in lower performance compared to our result (we set the batch size of 32).
If GPU memory is limited, I recommend you train TRACER using a smaller backbone network (e.g., TE-4 or 5) with batch size of 32.
Our result was reproduced at #2.

**Comment by aviadmx** [comment]
Out of curiosity, why would the batch size affect performance so drastically here?  
There's no hard mining scheme or something that directly utilizes the batch size, and as explained [here](https://stats.stackexchange.com/questions/164876/what-is-the-trade-off-between-batch-size-and-number-of-iterations-to-train-a-neu) smaller batch sizes usually helps the accuracy of the model.  
Anyway I'll try to train a smaller model and will report the results here, thanks

**Comment by Karel911** [comment]
Actually, when we experimented with the multiple ranges of batch size (i.e., 4 to 128), the network performance gradually increased within the batch size of 32.
Using more than the batch size of 64, the performance decreased or showed similar to that of 32. 
In my opinion, the 32 is too small for training DUTS-TR.
