### ISSUE TITLE
Changing black background to transparent

### ISSUE THREAD

**Issue by aycaecemgul** [Karel911/TRACER#21]
Hello, thanks for the code and paper. Amazing work! I was doing some tests and the model works very great. I wanted to see the results when background is transparent but i realized there is a black hue near edges when i applied the code below to change the background. I know that your project is RGB based but i wonder is there a workaround for me to get the results without black background or is it impossible? Thanks in advance.

img is the result of the model.
    color = (0, 0, 0)
    mask = np.where((img == color).all(axis=2), 0, 255).astype(np.uint8)
    result = img.copy()
    result = cv2.cvtColor(result, cv2.COLOR_BGR2BGRA)
    result[:, :, 3] = mask

model result:
![cat](https://user-images.githubusercontent.com/50622243/172838693-066e8d4a-3ad9-4732-ae5a-51fe0c3bb20e.png)
code result:
![result](https://user-images.githubusercontent.com/50622243/172838714-0f275fee-aff0-4016-85b5-afe39c607a30.png)
original image:
![cat](https://user-images.githubusercontent.com/50622243/172838775-1a4de977-52f7-4fea-b5cb-6cd2111295cb.png)

**Comment by wooseok-shin** [comment]
Hi,
Thank you for your interest in our research.

we have updated inference.py to reflect your suggestion.

Using the updated code, we confirmed that some of the black lines disappeared as follows:
![image](https://user-images.githubusercontent.com/46666862/174314293-da0f9c73-6735-4012-9655-e340dfc251c1.png)

This post-processing method has one hyper-parameter (threshold).
We haven't tested it on many images, but the threshold between 200 and 250 probably works.
