### ISSUE TITLE
GPU memory questions

### ISSUE THREAD

**Issue by DeepHM** [Karel911/TRACER#25]
Hello.
Thank you for your wonderful research.

I have a simple question.
I want to know the GPU memory usage for this research.
Thank you.

**Comment by Karel911** [comment]
Hi,
If you want to reproduce all results (TE1 to TE7), at least 8x GPUs (32G) are required (We used 8x V100).
A single GPU having 24G can reproduce the results up to TE3 with a batch size of 32.

**Comment by DeepHM** [comment]
Thank you!
