### ISSUE TITLE
Mask Generation?

### ISSUE THREAD

**Issue by LBNord** [Karel911/TRACER#3]
Hello! And thank you for this work. I was curious if you would be releasing or amending (or if I missed it in your paper) the mask generation part of your testing code? To try against more complicated imagery in visual form?

**Comment by wooseok-shin** [comment]
Hi,
We have updated line 272 and line 33 in [trainer.py](https://github.com/Karel911/TRACER/blob/main/trainer.py/#L272) and [config.py](https://github.com/Karel911/TRACER/blob/main/config.py/#L33), respectively.
If you want to save the prediction map, you can set save_map=True in arguments.
`python main.py test --exp_num 0 --arch 0 --img_size 320 --save_map=True`

**Comment by LBNord** [comment]
Thank you kindly!
