### ISSUE TITLE
About the edge folder

### ISSUE THREAD

**Issue by GuHuangAI** [Karel911/TRACER#4]
I notice that there is a edge folder in dataset, however, I didn't find this folder of DUTS or DUTO. 
How to generate these edge folders?

**Comment by Karel911** [comment]
Hi,
You don't need to prepare the edge folder for DUT-O dataset.
You can get the edge ground truth for DUTS dataset in [here](https://drive.google.com/file/d/1Xl-OwmbkmB1dnvIrcLq3OPQjQnieynpk/view).

**Comment by GuHuangAI** [comment]
> Hi, You don't need to prepare the edge folder for DUT-O dataset. You can get the edge ground truth for DUTS dataset in [here](https://drive.google.com/file/d/1Xl-OwmbkmB1dnvIrcLq3OPQjQnieynpk/view).

Thanks a lot. And are there any other edge folders for other datasets?

**Comment by Karel911** [comment]
Thank you for your interest in our research.
The other datasets (i.e., except for DUTS-TE) were used for inference, so there are no other edges at the other ones.
