### ISSUE TITLE
how to create the edge mask

### ISSUE THREAD

**Issue by hackkhai** [Karel911/TRACER#7]
Can you please share the code for creating the edge data from the alpha layer, so that we could retrain it with our own data
Thanks!

**Comment by Karel911** [comment]
Hi,
We have released the [edge_generator.py](https://github.com/Karel911/TRACER/blob/main/edge_generator.py).
Now you can apply it to your own dataset.

Thanks.

**Comment by hackkhai** [comment]
Thanks!
